<?php
// students_payment.php

$host = "localhost";
$user = "root";
$pass = "";
$db = "student_dashboard";
$conn = new mysqli($host, $user, $pass, $db);

if ($conn->connect_error) {
  die("DB Connection Failed: " . $conn->connect_error);
}
$conn->set_charset("utf8");

// ================= FETCH DETAILS =================
if (isset($_GET['fetch']) && isset($_GET['student_id'])) {
  $id = intval($_GET['student_id']);
  $q = $conn->query("SELECT s.id as roll_no, s.student_name, s.father_name, c.name as course_name, c.fee as course_fee, s.fee_status
                     FROM students s 
                     JOIN courses c ON s.course = c.id 
                     WHERE s.id=$id");
  if ($q && $q->num_rows > 0) {
    echo json_encode($q->fetch_assoc());
  } else {
    echo json_encode(["error" => "Student not found."]);
  }
  exit;
}

// ================= PAYMENT SUBMIT =================
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
  $student_id = intval($_POST['student_id']);

  $stmt = $conn->prepare("UPDATE students SET fee_status = 'PAID' WHERE id = ?");
  $stmt->bind_param("i", $student_id);

  if ($stmt->execute()) {
    $student_name = $_POST['student_name'] ?? "Unknown";
    $total_fee = $_POST['total_fee'] ?? "0";
    $biller_id = uniqid("NES_");
    header("Location: students_payment.php?status=success&biller_id=$biller_id&student=" . urlencode($student_name) . "&total=$total_fee&sid=$student_id");
  } else {
    header("Location: students_payment.php?status=error");
  }
  exit;
}

// ================= RECEIPT PDF =================
if (isset($_GET['receipt']) && isset($_GET['student_id']) && isset($_GET['biller_id'])) {
  require_once("tcpdf/tcpdf.php");

  $student_id = intval($_GET['student_id']);
  $biller_id = $_GET['biller_id'];

  $q = $conn->query("SELECT s.id as roll_no, s.student_name, s.father_name, c.name as course_name, c.fee as course_fee 
                     FROM students s 
                     JOIN courses c ON s.course = c.id 
                     WHERE s.id=$student_id LIMIT 1");

  if (!$q || $q->num_rows == 0) {
    die("Invalid student.");
  }
  $stu = $q->fetch_assoc();


  $pdf = new TCPDF('P', 'mm', array(148, 170), true, 'UTF-8', false);
  $pdf->SetCreator(PDF_CREATOR);
  $pdf->SetAuthor("NES SCHOOL");
  $pdf->SetTitle("Fee Payment Voucher");
  $pdf->SetAutoPageBreak(false, 0);
  $pdf->AddPage();

  // Border
  $pdf->SetLineWidth(0.5);
  $pdf->Rect(5, 5, 138, 160);

  // Header
  $pdf->SetFont("helvetica", "B", 20);
  $pdf->Cell(0, 15, "NES SCHOOL", 0, 1, "C");
  $pdf->Ln(5);

  // Heading
  $pdf->SetFont("helvetica", "B", 16);
  $pdf->Cell(0, 10, "FEE PAYMENT VOUCHER", 0, 1, "C");
  $pdf->Ln(15);

  // Details table
  $pdf->SetFont("helvetica", "", 12);
  $html = "
  <table border='1' cellpadding='6'>
    <tr><td><b>Roll No:</b></td><td>{$stu['roll_no']}</td></tr>
    <tr><td><b>Biller ID:</b></td><td>{$biller_id}</td></tr>
    <tr><td><b>Student Name:</b></td><td>{$stu['student_name']}</td></tr>
    <tr><td><b>Father Name:</b></td><td>{$stu['father_name']}</td></tr>
    <tr><td><b>Course:</b></td><td>{$stu['course_name']}</td></tr>
    <tr><td><b>Course Fee:</b></td><td>Rs. {$stu['course_fee']}/-</td></tr>
  </table>";
  $pdf->writeHTML($html, true, false, true, false, '');

  // Stamp
  if (file_exists("image/stamp.png")) {
    $pdf->Image("image/stamp.png", 80, 85, 45, 45, '', '', '', false, 300, '', false, false, 0, true, false, false);
  }


  $pdf->SetY(160);
  $pdf->SetFont("helvetica", "I", 10);
  $pdf->Cell(0, 0, "This voucher is generated by NES School", 0, 0, "C");

  $pdf->Output("Fee_Voucher_{$stu['roll_no']}.pdf", "I");
  exit;
}

?>

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <title>Student Fee Payment</title>
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <link rel="icon" href="image/nes_school.png">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css" />
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@400;600;700&display=swap');

    body {
      min-height: 100vh;
      display: flex;
      align-items: center;
      justify-content: center;
      background: linear-gradient(135deg, #0f2027, #203a43, #2c5364);
      padding: 28px;
      font-family: "Poppins", sans-serif;
      color: #fff;
    }

    /* Card Container */
    .card {
      width: 440px;
      background: rgba(255, 255, 255, 0.07);
      border-radius: 18px;
      padding: 28px 26px;
      backdrop-filter: blur(18px) saturate(180%);
      border: 1px solid rgba(255, 255, 255, 0.15);
      box-shadow: 0 12px 35px rgba(0, 0, 0, 0.6);
      transition: all 0.3s ease-in-out;
    }

    .card:hover {
      transform: translateY(-6px);
      box-shadow: 0 18px 40px rgba(0, 0, 0, 0.7);
    }

    /* Title */
    .title {
      color: #FFD700;
      font-weight: 700;
      font-size: 22px;
      text-align: center;
      margin-bottom: 20px;
      letter-spacing: 1px;
      text-transform: uppercase;
    }

    /* Input Fields */
    .field {
      position: relative;
      margin-top: 16px;
    }

    input {
      width: 100%;
      padding: 14px 16px;
      border-radius: 10px;
      border: none;
      background: rgba(255, 255, 255, 0.12);
      color: #fff;
      font-size: 15px;
      transition: all 0.3s ease;
    }

    input:focus {
      outline: none;
      background: rgba(255, 255, 255, 0.18);
      box-shadow: 0 0 0 2px #FFD70055;
    }

    input[readonly] {
      background: rgba(255, 255, 255, 0.09);
      color: #ddd;
    }

    /* Icons inside inputs */
    .icon {
      position: absolute;
      right: 14px;
      top: 50%;
      transform: translateY(-50%);
      color: #FFD700;
      font-size: 16px;
    }

    /* Payment Button */
    button.pay {
      width: 100%;
      margin-top: 22px;
      padding: 14px;
      border-radius: 12px;
      border: none;
      background: linear-gradient(135deg, #FFD700, #f39c12);
      color: #111;
      font-weight: 700;
      font-size: 15px;
      cursor: pointer;
      transition: all 0.3s ease;
      box-shadow: 0 10px 25px rgba(0, 0, 0, 0.45);
    }

    button.pay:hover {
      background: linear-gradient(135deg, #ffea70, #ffb84d);
      transform: translateY(-2px);
      box-shadow: 0 12px 30px rgba(0, 0, 0, 0.55);
    }

    /* Receipt Section */
    #receipt-box {
      display: none;
      text-align: center;
      margin-top: 18px;
    }

    #download-receipt {
      display: inline-block;
      width: 100%;
      padding: 14px;
      text-decoration: none;
      border-radius: 12px;
      background: linear-gradient(135deg, #FFD700, #f39c12);
      color: #111;
      font-weight: 700;
      font-size: 15px;
      cursor: pointer;
      transition: all 0.3s ease;
      box-shadow: 0 10px 25px rgba(0, 0, 0, 0.45);
    }

    #download-receipt:hover {
      background: linear-gradient(135deg, #ffea70, #ffb84d);
      transform: translateY(-2px);
    }

    /* Help Text */
    .help {
      font-size: 12px;
      color: rgba(255, 255, 255, 0.7);
      margin-top: 14px;
      text-align: center;
    }
  </style>
</head>

<body>
  <div class="card">
    <div class="title">💳 Student Fee Payment</div>
    <form method="POST" action="">
      <div class="field">
        <input id="student_id" name="student_id" type="number" placeholder="Enter Student ID" required />
        <i class="fas fa-id-card icon"></i>
      </div>
      <div class="field">
        <input id="student_name" name="student_name" type="text" placeholder="Student Name" readonly />
        <i class="fas fa-user icon"></i>
      </div>
      <div class="field">
        <input id="father_name" name="father_name" type="text" placeholder="Father Name" readonly />
        <i class="fas fa-user-tie icon"></i>
      </div>
      <div class="field">
        <input id="course_name" name="course_name" type="text" placeholder="Course Name" readonly />
        <i class="fas fa-book icon"></i>
      </div>
      <div class="field">
        <input id="course_fee" name="total_fee" type="text" placeholder="Course Fee (Rs)" readonly />
        <i class="fas fa-wallet icon"></i>
      </div>
      <button class="pay" type="submit"><i class="fas fa-check-circle"></i> Pay Fee</button>
    </form>

    <div id="receipt-box">
      <a id="download-receipt" href="#" target="_blank">📄 Download PDF Receipt</a>
    </div>
    <br>
    <div class="help">Enter ID and move out of field to auto-fill details.</div>
  </div>

  <script>
    $(function () {
      toastr.options = { closeButton: true, progressBar: true, positionClass: "toast-top-right", timeOut: 3000 };

      // fetch details
      $('#student_id').on('blur', function () {
        let id = $(this).val().trim();
        if (!id) return;
        fetch(`students_payment.php?fetch=1&student_id=${id}`)
          .then(r => r.json())
          .then(data => {
            if (data.error) {
              toastr.warning(data.error);
              $('#student_name,#father_name,#course_name,#course_fee').val('');
            } else {
              $('#student_name').val(data.student_name);
              $('#father_name').val(data.father_name);
              $('#course_name').val(data.course_name);
              $('#course_fee').val(data.course_fee);
            }
          })
          .catch(() => toastr.error('Server error while fetching student.'));
      });

      // show status
      const params = new URLSearchParams(window.location.search);
      if (params.get('status') === 'success') {
        let biller = params.get('biller_id');
        let sid = params.get('sid');
        toastr.success('Fee paid successfully!');
        $('#download-receipt').attr('href', `students_payment.php?receipt=1&student_id=${sid}&biller_id=${biller}`);
        $('#receipt-box').show();
        if (history.replaceState) history.replaceState(null, '', window.location.pathname);
      } else if (params.get('status') === 'error') {
        toastr.error('Error while paying fee.');
        if (history.replaceState) history.replaceState(null, '', window.location.pathname);
      }
    });
  </script>
</body>

</html>